### ISSUE TITLE
Bulk Creation

### ISSUE THREAD

**Issue by DN0000** [daxm/fmcapi#11]
Hi There, 

I see it is possible to perform bulk creation directly via the FMC API

Is this supported on fmcapi?

**Comment by daxm** [comment]
I don't believe it will work.  My logic in NOT programming for bulk POSTs is that you can queue up your changes in your Python script and just loop through them.  I know that is as efficient or quick as a bulk POST but that was how the program was written.

Could fmcapi be changed to support bulk POSTs?  I'm sure it could!  I'm totally open to working with anyone who'd like to take that challenge on!
