### ISSUE TITLE
Indentation error in api_objects.py

### ISSUE THREAD

**Issue by karmicgeezer** [daxm/fmcapi#17]
def destination_intf(self,name):
        logging.debug("In destination_intf() for ManualNatRules class.")
        intf_obj = InterfaceObject(fmc=self.fmc).get()
        items = intf_obj.get('items', [])
        new_intf = None
        for item in items:
            if item["name"] == name:
                new_intf = {'id': item['id'], 'type': item['type']}
                break
        if new_intf == None:
            logging.warning('Interface Object "{}" is not found in FMC.  Cannot add to destinationInterface.'.format(name))
        else:
            if new_intf.type == "InterfaceGroup" and len(new_intf.items) > 1:
            --> self.destinationInterface = new_intf <-- missing indentation
            logging.info('Interface Object "{}" added to NAT Policy.'.format(name))

**Comment by parkerbrother1** [comment]
@daxm pypi needs to be updated

**Comment by daxm** [comment]
Pushed 20180610.0 version.
