### ISSUE TITLE
APIClassTemplate(object) .get function issue

### ISSUE THREAD

**Issue by omni1504** [daxm/fmcapi#2]
Dax,

There is one suggestion for improvement I need to flag: in my case I am using your package to get Access Rules for optimization from a really busy box (23K Access Rules in a policy - this is the reason for a need to opimize).

Python/FMC/whatever just cannot handle retrieval of such a big list via .get (times out, FMC resets, etc), so I need to use ? filters in my request, for example:

https://<IP>/api/fmc_config/v1/domain/<ID>/policy/accesspolicies/00A6CAE6-686A-0ed3-0000-313532636857/accessrules?limit=10

But your generic .get function, if it does not see ID or name, is using the following constuct:
            url = '{}?expanded=true'.format(self.URL)
            response = self.fmc.send_to_api(method='get', url=url)
So it is adding this ? and does not allow me to use filters unless I change package itself (which I did).

How about changing this function so we could add arbitrary filters/parameters to get? That will mean that this needs to be changed so it could check for a trailing ? in an self.URL and add, if needed, otherwise add &.

Thank you!

Amir

**Comment by daxm** [comment]
Thank you for the note and nice comment.  Have you written a patch to fix this issue?  If not, we need to find someone to help as I can no longer focus on this project.  :-(

I don't mind hosting the repo and updated PyPi as/when necessary but I just don't have the cycles to code against it anymore.

**Comment by daxm** [comment]
Update:  No guarantee as of yet but I'm considering starting work on this again... if I can find the time to do so.  :-)

**Comment by daxm** [comment]
I believe this is fixed to how you'd like it.

You can now pass "limit=X" to limit the responses per page.  The default limit in FMC is 20 but the default in fmcapi is 25 (just to show it works).  You can issue the limit at FMC instationation or pass a limit variable in the get() request.
