### ISSUE TITLE
Documentation To Modify Existing objects

### ISSUE THREAD

**Issue by rlc9090gmail** [daxm/fmcapi#53]
**Is your feature request related to a problem? Please describe.**
I can't fine any documentation about using fmcapi to modify  existing objects. I am trying to modify a network group object to add more ip addresses to it.  I would also like to modify existing rules to add destination ports or destination addresses

**Describe the solution you'd like**
I would like update documentation with some examples of modifying objects.

**Comment by daxm** [comment]
While composing this answer I notice there isn't a "unit-test" for NetworkGroups.  I'll work on getting one built.

(Note:  The following is pseudo-code.  I just typed it here and didn't actually run it as a program.)
Try something like this to get the current object:
```
net_group = fmcapi.NetworkGroups(fmc=fmc1, name="Existing Name")
net_group.get()
```

Then make whatever additions/subtractions/modifications needed:
```
net_group.named_networks(action="add", name="blah")
net_group.unnamed_networks(action="remove", value="1.1.1.0/24")
```

Then push back into FMC:
```
net_group.post()
```

**Comment by daxm** [comment]
Did this work for you?

**Comment by rcsnow** [comment]
I have not  had  a chance to try  it yet.  I will update when I have. Thanks  for the pauedo code.

**Comment by daxm** [comment]
status?

**Comment by rlc9090gmail** [comment]
Have not had the opportunity yet. We are experiencing other non api related issues with 6.5.

**Comment by rlc9090gmail** [comment]
This can closed.
