### ISSUE TITLE
Creating NetworkGroups

### ISSUE THREAD

**Issue by rmv-first** [daxm/fmcapi#55]
Hello!

I can't find any documentation about using fmcapi to create NetworksGroups with 2 literal Networks. 
I would like to achieve the following:
![Снимок](https://user-images.githubusercontent.com/55360980/72516242-63c49700-3862-11ea-9bb1-254319a12f33.PNG)
Now there is a way to create single object Network for 7.7.7.0/29 and single object Network for 8.8.8.0/29 and сombine them in one group. It is not very convenient and flexible.

**Comment by marksull** [comment]
```
from fmcapi.fmc import FMC
from fmcapi.api_objects import NetworkGroups

with FMC(
    host="hostname",
    username="username",
    password="password",
    autodeploy=False,
) as fmc:
    group = NetworkGroups(fmc=fmc, name="test_network_object")
    group.unnamed_networks(action="add", value="10.0.0.0/24")
    group.unnamed_networks(action="add", value="11.0.0.0/24")
    group.post()
```
