### ISSUE TITLE
FMC ACP Rule Boolean Parameters

### ISSUE THREAD

**Issue by absolute450** [daxm/fmcapi#58]
Good day, 

I'm very newbie with python scripting. I am trying to use the FMC API to create a rule which I do succeed in. The problem I encounter is that I am trying to activate the "Log at Begining" and 'Log at End" checkbox in the rule but I cannot seem to get it working. At first I was creating the rule and it was disabled but I did manage to have it enabled. I first tried to do something like acpRule.enabled = True but it didn't work. Reading some other issues I managed to find that it actually didn't work anymore so someone suggested passing the boolean as a parameter of the put() function so I did acpRule.put(enabled=True) and that got my rule enabled. I'm trying to do the same with the logBegin and logEnd but whatever I try it doesn't seem to work. Here is a sample of my code. Note that I am doing an Excel file input for the variables because eventually I want to be able to bulk import rules. 

with FMC(host=host, username=username, password=password, autodeploy=autodeploy) as fmc1:
    wb = xl.load_workbook('rules.xlsx')
    acpRule = AccessRules(fmc=fmc1, acp_name='My-ACP-Rule')
    rule_sheet = wb['RulesCreation']
    for row in range(2, rule_sheet.max_row + 1):
        rule = setRuleVar()
        acpRule.name = rule['name']
        acpRule.action = rule['action']
        acpRule.source_zone(action='add', name=rule['srcZone'])
        acpRule.source_network(action='add', name=rule['srcNetwork'])
        acpRule.source_port(action='add', name=rule['srcPort'])
        acpRule.destination_zone(action='add', name=rule['destZone'])
        acpRule.destination_network(action='add', name=rule['destNetwork'])
        acpRule.destination_port(action='add', name=rule['destPort'])
        acpRule.variable_set(action='set', name=rule['varSet'])
        acpRule.intrusion_policy(action='set', name=rule['intruPol'])
        acpRule.vlan_tags(action='add', name=rule['VlanTag'])
        acpRule.post()
        acpRule.get()
        acpRule.put(enabled=True)
        acpRule.put(logBegin=True)
        acpRule.put(logEnd=True)

This is the error message I get when trying to run this script. Note it fails at the logBegin=True

Traceback (most recent call last):
  File "C:/Users/MyUsername/PycharmProjects/FMC-API/CreateRules.py", line 71, in <module>
    acpRule.put(logBegin=True)
  File "C:\Users\MyUsername\PycharmProjects\FMC-API\venv\lib\site-packages\fmcapi\api_objects\apiclasstemplate.py", line 306, in put
    self.parse_kwargs(**response)
TypeError: parse_kwargs() argument after ** must be a mapping, not NoneType

I tried to do some acpRule.get() in between the put() but I still get the same behaviour. I don't understand why the enabled Boolean works and not the other ones.

**Comment by marksull** [comment]
It looks like FMCAPI got an unexpected response from the FMC. Turn on debugging and see if you get a clue from the debugging output. To turn on debugging, add debug=True when you setup your FMC connection.

**Comment by absolute450** [comment]
Found out that the unexpected response from the FMC was caused because when I try to activate the logBegin and logEnd I had not yet activated the sendEventsToFMC trigger.
