### ISSUE TITLE
In accessrules.py, enableSyslog is not part of the VALID_JSON_DATA

### ISSUE THREAD

**Issue by fredfire** [daxm/fmcapi#59]
When creating a rule, and trying to enable default syslog, the accessrule class is rejecting the enablesyslog bool. I made sure it was a valid json entry by comparing two rules with and without syslog enabled.

I made my code work by modifying the accessrules.py manually. I added the enableSyslog value in the VALID_JSON_DATA.

Is there another way to enable that syslog? If not, please add it to the master branch. 

Thanks

**Comment by daxm** [comment]
Fixed.  Pushed to Master.  Created a new pip release too.  20200213.0
