### ISSUE TITLE
Host or network get operation not displaying expanded information 

### ISSUE THREAD

**Issue by MSD101** [daxm/fmcapi#64]
Thanks for this amazing work, this package helps me lot.

I am struggling with searching for the host or network using the name ( for example :  test (object name) and returning the expanded details ( like Name, value, description and id)

I tried to pass the expanded = True but no luck. 

It only output below information
INFO:root:GET success. Object with name: "test" and id: "0050569D-669F-0ed3-0000-146028913744" fetched from FMC.

Appreciate any guidance

Thanks

**Comment by daxm** [comment]
That "output" is just a "syslog" message.  If you want to see the object's information you'll need to use the Python print() function.  ```print(host1.name)``` for example.

**Comment by MSD101** [comment]
Thank you for quick reply

I am using below commands:

        name = input ('Enter IP Host Name:- ')
        iphost = fmcapi.Hosts(fmc=fmc1,name = name)
        iphost.get()

Should I add below
 print(iphost.name)?

Thanks again

**Comment by daxm** [comment]
Yep!  That will output the value for the "name" variable for the iphost Class object.

**Comment by MSD101** [comment]
Thanks a lot
