### ISSUE TITLE
Adding network group to another network group

### ISSUE THREAD

**Issue by MSD101** [daxm/fmcapi#69]
Hello!

I can't find any documentation about using fmcapi to create NetworksGroups and add another Networkgroup to that
I would like to achieve the following:

 Network group : -- test-nwgrp-all

and add two network groups test-nwgrp-01 and test-nwgrp-02 to above network group.

I know I can add named and unnamed network/hosts to the network group but Would it be possible to add another network group to network group.

Thanks for all your help

**Comment by MysticRyuujin** [comment]
You're looking for `action="addgroup"`

**Comment by MSD101** [comment]
Yes, that worked. 

Thanks a lot for your help.
