### ISSUE TITLE
acprule put() to add additional Zones and network/host not working

### ISSUE THREAD

**Issue by MSD101** [daxm/fmcapi#70]
Hi,

I am having trouble with using the acprule put operation to add src/dst and network/host. I am using below script

    acprule1.name = namer
    acprule1.action = "ALLOW"
    acprule1.enabled = False
    acprule1.sendEventsToFMC = True
    acprule1.logFiles = False
    acprule1.logBegin = True
    acprule1.logEnd = True
    acprule1.source_zone(action="add", name='inside')
    acprule1.destination_zone(action="add", name='outside')
    acprule1.source_network(action="add", name='test01')
    acprule1.destination_network(action="add", name='test02')
    acprule1.get()
    acprule1.put()

I am not getting error message but the rules doesn't get updated.

INFO:root:GET success. Object with name: "Test_Firewall-Policy" and id: "0050569D-669F-0ed3-0000-146028892" fetched from FMC.
INFO:root:GET success. Object with name: "inside" and id: "7b0035c4-4f4a-11ea-9876-a67125a5a" fetched from FMC.
INFO:root:Adding "inside" to sourceZones for this AccessRules.
INFO:root:GET success. Object with name: "outside" and id: "641c654e-4f4a-11ea-a9d3-d4e4358b1" fetched from FMC.
INFO:root:Adding "outside" to destinationZones for this AccessRules.
INFO:root:Adding "test01" to sourceNetworks for this AccessRules.
INFO:root:Adding "test02" to destinationNetworks for this AccessRules.
INFO:root:GET success. Object with name: "test-rule-012" and id: "0050569D-669F-0ed3-0000-000443653" fetched from FMC.
INFO:root:PUT success. Object with name: "test-rule-012" and id: "0050569D-669F-0ed3-0000-08443653" updated in FMC.
INFO:root:Test ACPRule done.

Appreciate  any help

Thanks

**Comment by daxm** [comment]
You might want to turn on debug=True in your fmc instantiation object call.
Also, depending on which version of FMC code you have (and which version of fmcapi code) there is a "bug" where you can't POST/PUT an AccessRule when sendEventsToFMC = True but logFiles = False.  Either both True or both False.

**Comment by MSD101** [comment]
Thanks for your help.

I turned on the debug=True  but not sure I need to look for to see why it's not updating.

I  am FMC version 6.3.0.3 (build 77) and tried changing both sendEventsToFMC = True and logFiles = True. But it's still not updating the rule.

Thanks

**Comment by MSD101** [comment]
Attached is debug output. Please let me know if I am doing anything wrong?

[debugoutput.txt](https://github.com/daxm/fmcapi/files/4458070/debugoutput.txt)

**Comment by MSD101** [comment]
After looking at the debug, found the issue. I was performing the get operation after setting the values for the zones,  I changed the order in script and it worked.

Thanks a lot for all your help. Really Appreciate.

[debugoutput3.txt](https://github.com/daxm/fmcapi/files/4458190/debugoutput3.txt)
