### ISSUE TITLE
adding acprule  and using category

### ISSUE THREAD

**Issue by MSD101** [daxm/fmcapi#71]
Hello,

I have created the Category under the ACP and trying to add the rule in that category. Not sure if this feature is supported or not

I am using below to pass the category information

acprule1 = fmcapi.AccessRules(fmc=fmc1, acp_name=namer,catagory = 'testing')

but I see in debug "section":"Default","category":"--Undefined--".

Just wondering if anyone was able to post/put rules under the category?

Thanks for your help.

**Comment by MSD101** [comment]
Found below link regarding the Access rules-Categories not supported with Rest API

https://community.cisco.com/t5/network-security/how-to-get-post-accessrule-categories/m-p/3380605#M9641

**Comment by daxm** [comment]
Good to know.  I guess we will have to revisit in the next code release and see if it is working.

Should we close this issue for now?

**Comment by MSD101** [comment]
Thanks
Yes, we can close this issue.
