### ISSUE TITLE
Add categories in access policy

### ISSUE THREAD

**Issue by rnuyttens** [daxm/fmcapi#76]
[**Is](url
[categories.zip](https://github.com/daxm/fmcapi/files/4774705/categories.zip)
)

I made a script for the creation of category in the access policy, however being beginning in python, could check if everything is good (and publish if you want)

Check with FMC 6.6 and 6.5

Best regards

**Comment by daxm** [comment]
Not saying this is wrong but it does break the methodology that we've been using for fmcapi.  Each class translates directly to an API feature from the FMC.  I don't see a specific API feature for "RuleCategories".  I'd suggest you re-work it into the AccessRules class.

**Comment by caballero-oscuro** [comment]
Hi daxm,

Seeing as this is an open issue, am I to assume that there isn't a way to account for 'categories' already present in the 'AccessRules' class?

**Comment by daxm** [comment]
Direct modification of Categories (get, post, put, delete) appears to 
have been added in v6.5.0.  Alas, the fmcapi package has not yet gotten 
that programmed out.  A quick look at the API guide makes me think it 
wouldn't be too hard to add in. 
https://www.cisco.com/c/en/us/td/docs/security/firepower/660/api/REST/firepower_management_center_rest_api_quick_start_guide_660/Objects_In_The_REST_API.html#id_118415

I'll put it on my todo list but I cannot guarantee any timeframe.

**Comment by caballero-oscuro** [comment]
No worries! Thanks for the response. Also, fmcapi has been a HUGE help to me and I just wanted to say thanks for doing this!

**Comment by daxm** [comment]
I'm glad it is helpful!

Do you want to take a stab at programming the Categories API features?  
You can take a look at something like the Ports API in fmcapi as a 
reference.

**Comment by kell4now** [comment]
I added support for categories quite some time back for ACP rules:
https://github.com/daxm/fmcapi/pull/31

**Comment by caballero-oscuro** [comment]
> I added support for categories quite some time back for ACP rules:
> #31

You're right, I do see that support added. However, I was only able to get it to work by adding "category" to:

VALID_FOR_KWARGS = VALID_JSON_DATA + [
        "acp_id",
        "acp_name",
        "insertBefore",
        "insertAfter",
        "section",
        "category"
    ]
It seems to be missing from the list. I'm still learning how this all works, so if I'm mistaken let me know. Thanks!

**Comment by kell4now** [comment]
@caballero-oscuro - ok, not sure why it was missing from that list. You can go ahead and create a branch add that in and submit a PR :)

**Comment by daxm** [comment]
I just added it to Master and pushed to GitHub.
