### ISSUE TITLE
"Type" error when calling FilePolicies for an access rule.

### ISSUE THREAD

**Issue by Td3v** [daxm/fmcapi#82]
Receiving error when attempting to add a file policy to an access rule. "'FilePolicies' object has no attribute 'type'"

I believe the issue is in the fmcapi/api_objects/policy_services/filepolicies.py file. FilePolicies are added in a very similar manner to IntrustionPolicies in that they require a type. I believe we need to update the file to use VALID_JSON_DATA = ["id", "name", "type"] just like in fmcapi/api_objects/policy_services/intrusionpolicies.py.

Are you able to test the ability to add a filepolicy to an access policy rule?

2020-09-30 20:59:13.973
GET success. Object with name: "File-Block-Policy" and id: "<policy_id>" fetched from FMC.
Information
2020-09-30 20:59:13.973
Waiting 15 seconds to allow the FMC to update the list of deployable devices.
Information
2020-09-30 20:59:28.989
Getting a list of deployable devices.
Information
2020-09-30 20:59:29.844
No devices need deployed.
Information
2020-09-30 20:59:29.845
'FilePolicies' object has no attribute 'type'

**Comment by daxm** [comment]
Nice catch!  I've added "type" to VALID_JSON_DATA and pushed a new release.  pip upgrade to 20201001.0.
If that doesn't work let me know so we can continue to iterate.

**Comment by Td3v** [comment]
That fixed it! Thanks so much for the quick response!
