### ISSUE TITLE
Add an escape method/message for invalid credentials

### ISSUE THREAD

**Issue by aegiacometti** [daxm/fmcapi#93]
When invalid credentials are used, exception rise

DEBUG:urllib3.connectionpool:https://fmcrestapisandbox.cisco.com:443 "POST /api/fmc_platform/v1/auth/generatetoken HTTP/1.1" 401 None
DEBUG:root:Response from generatetoken() post:
	url: https://fmcrestapisandbox.cisco.com/api/fmc_platform/v1/auth/generatetoken
	headers: {'Content-Type': 'application/json'}
	response: <Response [401]>
Traceback (most recent call last):
  File "ip_to_networkgroups.py", line 114, in <module>
    main(function, ip_address, network_group)
  File "ip_to_networkgroups.py", line 30, in main
    autodeploy=False) as fmc:
  File "/usr/local/lib/python3.6/dist-packages/fmcapi/fmc.py", line 130, in __enter__
    verify_cert=self.VERIFY_CERT,
  File "/usr/local/lib/python3.6/dist-packages/fmcapi/fmc.py", line 398, in __init__
    self.generate_tokens()
  File "/usr/local/lib/python3.6/dist-packages/fmcapi/fmc.py", line 453, in generate_tokens
    all_domain = json.loads(response.headers.get("DOMAINS"))
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

**Comment by daxm** [comment]
I too get hit by this and take FOREVER to figure out that I just typoed my password.  (Then I forget to do anything about it.)
I'll look into this but you seem already there?  Do you have a PR you can submit?

**Comment by aegiacometti** [comment]
Sure, yesterday I was working on both issues I wrote. But since I was modifying your code I decided to stop and ask the questions. I will try to work a bit more on this and I will let you know. I might not be able to found the prettiest solution but at least I will give some ideas.

**Comment by aegiacometti** [comment]
Hi just created the PR for this... please let me know what do you think

**Comment by aegiacometti** [comment]
solved in PR.
Thanks! wonderful experience contributing to this project.
